package nc.unc.vaadin.flow.polymer.iron.icons;

import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.dependency.NpmPackage;

@NpmPackage(value = "@polymer/iron-icons", version = IronIcons.VERSION)
@JsModule("@polymer/iron-icons/av-icons.js")
public enum IronAvIcons implements IronIconDefinition {
    ADD_TO_QUEUE,
    AIRPLAY,
    ALBUM,
    ART_TRACK,
    AV_TIMER,
    BRANDING_WATERMARK,
    CALL_TO_ACTION,
    CLOSED_CAPTION,
    EQUALIZER,
    EXPLICIT,
    FAST_FORWARD,
    FAST_REWIND,
    FEATURED_PLAY_LIST,
    FEATURED_VIDEO,
    FIBER_DVR,
    FIBER_MANUAL_RECORD,
    FIBER_NEW,
    FIBER_PIN,
    FIBER_SMART_RECORD,
    FORWARD_10,
    FORWARD_30,
    FORWARD_5,
    GAMES,
    HD,
    HEARING,
    HIGH_QUALITY,
    LIBRARY_ADD,
    LIBRARY_BOOKS,
    LIBRARY_MUSIC,
    LOOP,
    MIC,
    MIC_NONE,
    MIC_OFF,
    MOVIE,
    MUSIC_VIDEO,
    NEW_RELEASES,
    NOT_INTERESTED,
    NOTE,
    PAUSE,
    PAUSE_CIRCLE_FILLED,
    PAUSE_CIRCLE_OUTLINE,
    PLAY_ARROW,
    PLAY_CIRCLE_FILLED,
    PLAY_CIRCLE_OUTLINE,
    PLAYLIST_ADD,
    PLAYLIST_ADD_CHECK,
    PLAYLIST_PLAY,
    QUEUE,
    QUEUE_MUSIC,
    QUEUE_PLAY_NEXT,
    RADIO,
    RECENT_ACTORS,
    REMOVE_FROM_QUEUE,
    REPEAT,
    REPEAT_ONE,
    REPLAY,
    REPLAY_10,
    REPLAY_30,
    REPLAY_5,
    SHUFFLE,
    SKIP_NEXT,
    SKIP_PREVIOUS,
    SLOW_MOTION_VIDEO,
    SNOOZE,
    SORT_BY_ALPHA,
    STOP,
    SUBSCRIPTIONS,
    SUBTITLES,
    SURROUND_SOUND,
    VIDEO_CALL,
    VIDEO_LABEL,
    VIDEO_LIBRARY,
    VIDEOCAM,
    VIDEOCAM_OFF,
    VOLUME_DOWN,
    VOLUME_MUTE,
    VOLUME_OFF,
    VOLUME_UP,
    WEB,
    WEB_ASSET;
    
    public static final String COLLECTION = "av";
    
    public String collection() {
        return COLLECTION;
    }
    
}